services:
  cecy_db_nest:
    container_name: cecy_db_nest
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cecy

  api_nest_cecy:
    container_name: api_nest_cecy
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - cecy_db_nest
    volumes:
      - .:/cecy_api
